#Number of orders: 1
#Tasks: assembly
#Number of shipments: 1
#Insufficiently many products: No
#Part re-orientation: No
#In-process order update: No
#Dropped products: No
#In-process order interruption: No
#Faulty products: No
#Sensor blackout: No
#Time limit: No

options:
  insert_models_over_bins: true
  belt_population_cycles: 10
  insert_models_over_stations: true
  gazebo_state_logging: true
time_limit: -1

agv_infos:
  agv1:
    location: ks1
  agv2:
    location: ks2
  agv3:
    location: ks3
  agv4:
    location: ks4    
 
orders:
  # Example for tasking one robot to do assembly and one robot to do kitting
  order_0:
    priority: 1
    kitting_robot_health: 1 
    assembly_robot_health: 1 
    announcement_condition: time
    announcement_condition_value: 0.0
    kitting:
      shipment_count: 1
      agvs: [agv1]
      destinations: [as2]
      products:
        part_0:
          type: assembly_pump_red
          pose:
            xyz: [0.1, 0.1, 0]
            rpy: [0, 0, 0]
        part_1:
          type: assembly_pump_red
          pose:
            xyz: [-0.1, -0.1, 0]
            rpy: [0, 0, 0]

belt_models:
  assembly_pump_red:
    15.0:
      pose:
        xyz: [0.0, 4.3, 0.92]
        rpy: [0, 0, 0]

