#Number of orders: 1
#Tasks: assembly
#Number of shipments: 1
#Insufficiently many products: No
#Part re-orientation: No
#In-process order update: No
#Dropped products: No
#In-process order interruption: No
#Faulty products: No
#Sensor blackout: No
#Time limit: No

options:
  insert_models_over_bins: true
  belt_population_cycles: 10
  insert_models_over_stations: true
  gazebo_state_logging: true
time_limit: 500

agv_infos:
  agv1:
    location: ks1
 
  agv2:
    location: ks2

  agv3:
    location: ks3

  agv4:
    location: ks4    

orders:
  # Example for tasking one robot to do assembly and one robot to do kitting
  order_0:
    priority: 1
    kitting_robot_health: 1 
    assembly_robot_health: 1 
    announcement_condition: time
    announcement_condition_value: 0.0
    kitting:
      shipment_count: 1
      agvs: [agv1]
      destinations: [as2]
      products:
        part_0:
          type: assembly_battery_blue
          pose:
            xyz: [0.1, 0.1, 0]
            rpy: [0, 0, 'pi/3']
        part_1:
          type: assembly_sensor_green
          pose:
            xyz: [-0.1, 0.1, 0]
            rpy: [0, 0, 'pi/2']

  order_1:
    priority: 3
    kitting_robot_health: 1 
    assembly_robot_health: 1 
    announcement_condition: wanted_products
    announcement_condition_value: 1
    kitting:
      shipment_count: 1
      agvs: [agv2]
      destinations: [as1]
      products:
        part_0:
          type: assembly_battery_blue
          pose:
            xyz: [0.1, 0.1, 0]
            rpy: [0, 0, 0]
        part_1:
          type: assembly_sensor_green
          pose:
            xyz: [0, 0, 0]
            rpy: [0, 0, 'pi/4']
 
models_over_bins:
   bin4:
     models:
       assembly_battery_blue:
         xyz_start: [0.2, 0.2, 0.0]
         xyz_end: [0.4, 0.4, 0.0]
         rpy: [0, 0, 0]
         num_models_x: 2
         num_models_y: 2
   bin7:
     models:
       assembly_sensor_green:
         xyz_start: [0.2, 0.2, 0.0]
         xyz_end: [0.4, 0.4, 0.0]
         rpy: ['pi/3', 0, 0]
         num_models_x: 2
         num_models_y: 2

