#Number of orders: 2
#Tasks: kitting
#Number of shipments: 1
#Insufficiently many products: Yes
#Part re-orientation: Yes
#In-process order update: Yes
#Dropped products: No
#In-process order interruption: No
#Faulty products: Yes
#Sensor blackout: Yes
#Time limit: No

options:
  insert_models_over_bins: true
  belt_population_cycles: 10
  insert_models_over_stations: true
  gazebo_state_logging: true
time_limit: 500

agv_infos:
  agv1:
    location: ks1

  agv2:
    location: ks2

  agv3:
    location: ks3

  agv4:
    location: ks4    

orders:
  # Example for tasking one robot to do assembly and one robot to do kitting
  order_0:
    priority: 1
    kitting_robot_health: 1 
    assembly_robot_health: 1 
    announcement_condition: time
    announcement_condition_value: 0.0
    kitting:
      shipment_count: 1
      agvs: [agv1]
      destinations: [as2]
      products:
        part_0:
          type: assembly_pump_red
          pose:
            xyz: [0.1, 0.1, 0]
            rpy: ['pi', 0, 0]
        part_1:
          type: assembly_pump_red
          pose:
            xyz: [-0.1, -0.1, 0]
            rpy: [0, 0, 0]

  order_1:
    priority: 3
    kitting_robot_health: 1 
    assembly_robot_health: 1 
    announcement_condition: unwanted_products
    announcement_condition_value: 1
    kitting:
      shipment_count: 1
      agvs: [agv3]
      destinations: [as3]
      products:
        part_0:
          type: assembly_battery_blue
          pose:
            xyz: [0.1, 0.1, 0]
            rpy: [0, 0, 0]
        part_1:
          type: assembly_sensor_green
          pose:
            xyz: [-0.1, -0.1, 0]
            rpy: [0, 0, 0]

models_over_bins:
   bin1:
     models:
       assembly_pump_red:
         xyz_start: [0.2, 0.2, 0.0]
         xyz_end: [0.4, 0.4, 0.0]
         rpy: [0, 0, 0]
         num_models_x: 2
         num_models_y: 2

   bin7:
     models:
       assembly_battery_blue:
         xyz_start: [0.2, 0.2, 0.0]
         xyz_end: [0.4, 0.4, 0.0]
         rpy: [0, 0, 0]
         num_models_x: 2
         num_models_y: 2

sensor_blackout:
    product_count: 2
    duration: 10

faulty_products:
  - assembly_battery_blue_5

